# -*- coding: utf-8 -*-
"""final_project CS441V.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X7PWEBOGsOIo4aB7FweLZ44mPnXGnqC9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# install xlrd
!pip install xlrd

print ('xlrd installed!')

df = pd.read_csv('/content/netflix_titles.csv')
df.head(10)

# Xử lý cột ngày tháng: Ép kiểu về dạng datetime chuẩn.
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['year_added'] = df['date_added'].dt.year

# Lọc bỏ những bộ phim không có thông tin năm phát hành
df = df.dropna(subset=['year_added'])

# tách duration
df['duration_num'] = df['duration'].str.extract('(\d+)').astype(float)

"""# Xu hướng phát triển và chiến lược nội dung của Netflix được thể hiện như thế nào thông qua dữ liệu phim và TV Show?

# Xem sự phát triển của nền tảng

Ý nghĩa biểu đồ

Biểu đồ đường thể hiện số lượng Movie và TV Show được thêm vào nền tảng theo từng năm.

Giúp quan sát xu hướng phát triển nội dung theo thời gian
So sánh tốc độ tăng trưởng giữa Movie và TV Show
"""

# đếm số lượng theo năm và loại
grouped = df.groupby(['year_added', 'type']).size().unstack()

# vẽ biểu đồ
plt.figure()

plt.plot(grouped.index, grouped['Movie'], marker='o', label='Movie')
plt.plot(grouped.index, grouped['TV Show'], marker='o', label='TV Show')

plt.title('Số lượng Movie và TV Show theo thời gian')
plt.xlabel('Năm')
plt.ylabel('Số lượng')
plt.legend()
plt.grid()

plt.show()

"""Netflix tăng trưởng mạnh về nội dung theo thời gian, đặc biệt là Movie, cho thấy chiến lược mở rộng nhanh để thu hút người dùng.

# Chiến lược nội dung

Biểu đồ tròn thể hiện tỷ lệ phần trăm giữa Movie và TV Show.

Giúp ta thấy: loại nội dung nào chiếm ưu thế
"""

type_counts = df['type'].value_counts()

plt.figure()
plt.pie(type_counts, labels=type_counts.index, autopct='%1.1f%%')
plt.title('Tỷ lệ Movie vs TV Show')
plt.show()

"""# Thị trường mạnh nhất

Ý nghĩa biểu đồ

Biểu đồ cột thể hiện top các quốc gia sản xuất nhiều nội dung nhất.

Cho thấy: nội dung đến từ đâu, thị trường nào mạnh.
"""

# tách nhiều quốc gia trong 1 dòng
country_df = df.dropna(subset=['country'])
country_df = country_df.assign(country=country_df['country'].str.split(', ')).explode('country')

top_countries = country_df['country'].value_counts().head(10)

plt.figure()
sns.barplot(x=top_countries.values, y=top_countries.index)
plt.title('Top 10 quốc gia sản xuất nhiều nội dung nhất')
plt.xlabel('Số lượng')
plt.ylabel('Quốc gia')
plt.show()

"""Mỹ thường đứng đầu
→ trung tâm sản xuất nội dung lớn nhất

Các quốc gia khác như: Ấn Độ, Anh, Hàn Quốc đang tăng trưởng

# Thị hiếu người xem

Biểu đồ thể hiện các thể loại phổ biến nhất.

Giúp hiểu: người xem thích nội dung gì, nền tảng nên tập trung vào thể loại nào
"""

# tách genre
genre_df = df.dropna(subset=['listed_in'])
genre_df = genre_df.assign(genre=genre_df['listed_in'].str.split(', ')).explode('genre')

top_genres = genre_df['genre'].value_counts().head(10)

plt.figure()
sns.barplot(x=top_genres.values, y=top_genres.index)
plt.title('Top 10 thể loại phổ biến nhất')
plt.xlabel('Số lượng')
plt.ylabel('Thể loại')
plt.show()

"""# Nội dung dành cho trẻ em hay người lớn nhiều hơn?

Ý nghĩa biểu đồ:

Cho biết nội dung tập trung vào nhóm tuổi nào

Nhìn vào chiều cao cột → biết loại rating nào nhiều nhất
"""

valid_ratings = ['TV-MA','TV-14','TV-PG','R','PG-13','TV-Y','TV-Y7','PG','G','NR']
df = df[df['rating'].isin(valid_ratings)]

rating_counts = df['rating'].value_counts()

plt.figure(figsize=(10,5))
rating_counts.plot(kind='bar')

plt.title('Phân phối xếp hạng nội dung')
plt.xlabel('Rating')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45)

plt.grid(axis='y')
plt.tight_layout()
plt.show()

"""Biểu đồ cột này dùng để thể hiện số lượng nội dung theo từng mức rating (phân loại độ tuổi). value_counts() sẽ đếm số lần xuất hiện của từng loại rating (ví dụ: TV-MA, TV-14, PG,…). Sau đó plot(kind='bar') sẽ vẽ biểu đồ cột. nhìn vào biểu đồ, ta thấy một điểm khá rõ nội dung dành cho người lớn (TV-MA, TV-14) chiếm phần lớn. Netflix đang tập trung mạnh vào đối tượng người xem trưởng thành, thay vì trẻ em.

# Thời lượng phim phân bố ra sao?

Ý nghĩa:

Cho biết phim thường dài bao nhiêu phút

Cột cao nhất = khoảng thời lượng phổ biến nhất
"""

movies = df[df['type'] == 'Movie']

plt.figure(figsize=(10,5))
plt.hist(movies['duration_num'].dropna(), bins=30)

plt.title('Phân bổ thời lượng phim')
plt.xlabel('Duration (minutes)')
plt.ylabel('Number of Movies')

plt.grid()
plt.tight_layout()
plt.show()

"""Biểu đồ histogram này dùng để xem: Thời lượng phim (Movie) phân bố như thế nào
Cách hoạt động:
duration_num là thời lượng phim (đã tách từ "90 min"),
bins=30 nghĩa là chia dữ liệu thành 30 khoảng,
hist() sẽ đếm xem mỗi khoảng có bao nhiêu phim
Kết quả quan sát:  Phim tập trung nhiều nhất khoảng 90 – 120 phút

# Movie và TV Show khác nhau về: số lượng, thể loại

Số lượng Movie vs TV Show

Biểu đồ này được sử dụng để trả lời câu hỏi: Nền tảng có xu hướng tập trung vào Movie hay TV Show nhiều hơn?
"""

# số lượng
type_counts = df['type'].value_counts()

plt.figure(figsize=(8,5))

bars = plt.bar(type_counts.index, type_counts.values)

# thêm số lên đầu cột
for bar in bars:
    y = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, y, int(y),
             ha='center', va='bottom')

plt.title('Comparison of Movie and TV Show Counts', fontsize=14, fontweight='bold')
plt.xlabel('Content Type')
plt.ylabel('Number of Titles')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""Biểu đồ so sánh số lượng cho thấy Movie chiếm ưu thế về số lượng, phản ánh vai trò thu hút người xem nhanh chóng. Trong khi đó, TV Show dù ít hơn nhưng lại có giá trị trong việc duy trì sự gắn bó lâu dài, góp phần tạo nên một chiến lược nội dung cân bằng và hiệu quả.

so sánh thể loại giữa Movie và TV Show
"""

# Tách cột thể loại thành danh sách
df['genre'] = df['listed_in'].str.split(',')
df_exploded = df.explode('genre')
df_exploded['genre'] = df_exploded['genre'].str.strip()
# Tách dữ liệu thành Movie và TV Show
movies = df_exploded[df_exploded['type'] == 'Movie']
tvshows = df_exploded[df_exploded['type'] == 'TV Show']
# Đếm số lượng thể loại phổ biến nhất
movie_genre = movies['genre'].value_counts().head(10)
tv_genre = tvshows['genre'].value_counts().head(10)

# Biểu đồ bên trái: Movie
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
movie_genre.plot(kind='barh')
plt.title('Top Genres - Movie')
# Biểu đồ bên phải: TV Show
plt.subplot(1,2,2)
tv_genre.plot(kind='barh')
plt.title('Top Genres - TV Show')
plt.tight_layout()
plt.show()

"""Đối với Movie: Có nhiều thể loại khác nhau như: Action, Comedy, Drama
Phân bố khá đa dạng Điều này cho thấy:

Movie được thiết kế để phục vụ nhiều sở thích khác nhau,
Người xem có thể chọn nội dung phù hợp với mình

Đối với TV Show: tập trung nhiều vào một số thể loại như: Drama, Crime, Reality / TV Shows quốc tế

Điều này cho thấy: TV Show thường có cốt truyện dài và phát triển theo thời gian
Phù hợp với người xem thích theo dõi lâu dài

# So sánh với Project giữa kỳ

1.  Ở giữa kỳ, tụi em chủ yếu tập trung vào việc đọc dữ liệu và vẽ một vài
biểu đồ cơ bản để xem dữ liệu.
2.   Sang đến cuối kỳ, tụi em bắt đầu thay đổi cách làm bằng việc đặt ra một câu hỏi rõ ràng ngay từ đầu. Nhờ có định hướng cụ thể nên quá trình phân tích trở nên logic hơn.

1.   Tụi em chú ý làm sạch dữ liệu, xử lý các giá trị bị thiếu và đặc biệt là chuẩn hóa lại dữ liệu trước khi phân tích.
2.   Giữa kỳ: Trình bày rời rạc, theo từng biểu đồ,
Cuối kỳ: Có logic rõ ràng, đi theo từng câu hỏi
"""